### ISSUE TITLE
Photo "stack" functionality

### ISSUE THREAD

**Issue by SethAngell** [ORNL-DataViz/DataVizFrontend#4]
## Product Spec
In order to maintain visual consistency across platforms as well as maintaining proper aspect ratios, the photos will be held in a visual "deck of cards." As the user works their way through the stack, cards will fly left or right onto two additional stacks representing the correct and incorrect decisions. At any given time, the maximum number of images show should be 4: 1 on the center stack waiting to be decided upon, the top of the incorrect stack, the top of the correct stack, and one flying right or left to its new stack.

## Task Requirements
- [ ] Function to facilitate: Number of photos in a job / 10 = how many cards will have to be cycled through before one of the 10 cards representing the Job set are removed
- [ ] Transfer function to animate left and right movement of cards
- [ ] Stack(DS) function to keep track of the next card to be shown
- [ ] Asset creation to generate actual "cards" for the RawImage components to sit on top of
- [ ] Helper function to organize and assign variables and tags when a new trial is initiated
- [ ] Helper function to track every interaction a user has with a picture (i.e "said correct", "said undo", "said incorrect")
- [ ] Helper function to assign final distinction to every card based of stack (i.e. all cards in the "correct" stack have their ImageCorrect value compared against "True" and then the result it stored)
