### ISSUE TITLE
Streamlined User Interface

### ISSUE THREAD

**Issue by SethAngell** [ORNL-DataViz/DataVizFrontend#5]
# Plan 
Reduce the number of UI components by displaying only one undo option and one photo to decide on. Track progress using a progress bar

# Tasks
- [ ] Write function to resize photo container to a consistent area of 250,000 (500x500)
- [ ] Write Linked-List data structure to manage the generation, loading, and unloading of Texture2D objects onto the GPU
- [ ] Write function to progress the progress bar based off of the the active node
- [ ] Write function to handle the grey-scaling of the last decisioned photo
